name: Calculator Tests

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 1) Check out the source code so that the workflow can access it.
      - uses: actions/checkout@v2
      # 2) Set up the .NET CLI environment for the workflow to use.
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"
      # 3) Restore the dependencies and tools of a project or solution.
      - name: Install dependencies
        run: dotnet restore
      # 4) Build a project or solution and all of its dependencies.
      - name: Build
        run: dotnet build --configuration Release
      - name: Run NUnit tests
        run: dotnet test --configuration Release --no-build --verbosity normal --filter "Name=CoreTests"